apiVersion: v1
kind: Pod
metadata:
   name: mysql
   labels:
       app: mysql
spec:
   containers:
   - name: mysql
     image: mysql:5
     env:
       - name: MYSQL_ROOT_PASSWORD
         value: fleetman
       - name: MYSQL_DATABASE
         value: fleerman
---
apiVersion: v1
kind: Service
metadata:
    name: database
spec:
   selector:
     app: mysql
   ports:
   - port: 3306
   type: ClusterIP
